version: '3.4'

services:
  A:
    image: stefanolupo/ndn:ndn-node
    environment:
      - NLSR_CONFIG=/NLSR/linear-three/nodeA-nlsr.conf
      - GAME=java -jar /NdnGame/NdnGameLibGdxDesktop-1.0-SNAPSHOT.jar -a wsp -hl -n nodeA
      - METRICS_DIR=/metrics
    volumes:
      - /home/stefano/projects/NdnGame/NdnGameLibGdxDesktop/build/libs:/NdnGame
      - /home/stefano/projects/ndn-script/nlsr/topologies:/NLSR
    stdin_open: true
    tty: true
    hostname: nodeA
    networks:
      private-ndn-overlay:
        aliases:
          - nodea.ndngame.com
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    healthcheck:
      test: docker-healthcheck
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  B:
    image: stefanolupo/ndn:ndn-node
    environment:
      - NLSR_CONFIG=/NLSR/linear-three/nodeB-nlsr.conf
      - GAME=java -jar /NdnGame/NdnGameLibGdxDesktop-1.0-SNAPSHOT.jar -a wsp -hl -n nodeB
      - METRICS_DIR=/metrics
    volumes:
      - /home/stefano/projects/NdnGame/NdnGameLibGdxDesktop/build/libs:/NdnGame
      - /home/stefano/projects/ndn-script/nlsr/topologies:/NLSR
    stdin_open: true
    tty: true
    hostname: nodeB
    networks:
      private-ndn-overlay:
        aliases:
          - nodeb.ndngame.com
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    healthcheck:
      test: docker-healthcheck
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  C:
    image: stefanolupo/ndn:ndn-node
    environment:
      - NLSR_CONFIG=/NLSR/linear-three/nodeC-nlsr.conf
      - GAME=java -jar /NdnGame/NdnGameLibGdxDesktop-1.0-SNAPSHOT.jar -a wsp -hl -n nodeC
      - METRICS_DIR=/metrics
    volumes:
      - /home/stefano/projects/NdnGame/NdnGameLibGdxDesktop/build/libs:/NdnGame
      - /home/stefano/projects/ndn-script/nlsr/topologies:/NLSR
    stdin_open: true
    tty: true
    hostname: nodeC
    networks:
      private-ndn-overlay:
        aliases:
          - nodec.ndngame.com
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    healthcheck:
      test: docker-healthcheck
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  X:
    image: stefanolupo/ndn:ndn-node
    environment:
      - NLSR_CONFIG=/NLSR/linear-three/nodeX-nlsr.conf
      - GAME=java -jar /NdnGame/NdnGameLibGdxDesktop-1.0-SNAPSHOT.jar -a wsp -hl -n nodeX
      - METRICS_DIR=/metrics
    volumes:
      - /home/stefano/projects/NdnGame/NdnGameLibGdxDesktop/build/libs:/NdnGame
      - /home/stefano/projects/ndn-script/nlsr/topologies:/NLSR
    stdin_open: true
    tty: true
    hostname: nodeX
    networks:
      private-ndn-overlay:
        aliases:
          - nodex.ndngame.com
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    healthcheck:
      test: docker-healthcheck
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s


networks:
  private-ndn-overlay:
    driver: overlay
