#! /bin/bash

# declare -a default_nodenames=("A" "B" "C" "D" "E" "F" "G" "X")
# declare -a default_machinenames=("m1" "m2" "m3" "m4" "m5" "m6" "m7" "m8" "m9" "m10")

prefix=$1
outdir=$2
use_machine=$3

function get_for_containers() {
    docker container ls -q | while read -r container ; do
        echo "Getting from $container"
        docker cp $container:/metrics/. $outdir
    done
}

function get_for_machines() {

    docker-machine ls -q | while read -r machine ; do
        echo "Getting from $machine"
        eval $(docker-machine env $machine)
        get_for_containers
    done
}


if [ -n "$use_machine" ]; then
    echo "Getting for machines"
    get_for_machines
else
    echo "Getting for containers"
    get_for_containers
fi
