version: '2'

services:
  A:
      image: ndn-node
      environment:
        - NLSR_CONFIG=$TOPOLOGY_DIR/nodeA-nlsr.conf
        - GAME=$GAME_BASE nodeA
      volumes: 
        - $GAME_JAR_SRC:$GAME_JAR_DEST
        - $NLSR_CONFIG_SRC:$NLSR_CONFIG_DEST
      stdin_open: true
      tty: true
      networks:
        ndn:
          ipv4_address: 172.19.0.10
  B:
      image: ndn-node
      environment:
        - NLSR_CONFIG=$TOPOLOGY_DIR/nodeB-nlsr.conf
        - GAME=$GAME_BASE nodeB
      volumes: 
        - $GAME_JAR_SRC:$GAME_JAR_DEST
        - $NLSR_CONFIG_SRC:$NLSR_CONFIG_DEST
      stdin_open: true
      tty: true
      networks:
        ndn:
          ipv4_address: 172.19.0.11
  C:
    image: ndn-node
    environment:
      - NLSR_CONFIG=$TOPOLOGY_DIR/nodeC-nlsr.conf
      - GAME=$GAME_BASE nodeC
    volumes: 
      - $GAME_JAR_SRC:$GAME_JAR_DEST
      - $NLSR_CONFIG_SRC:$NLSR_CONFIG_DEST
    stdin_open: true
    tty: true
    networks:
      ndn:
        ipv4_address: 172.19.0.12
  D:
    image: ndn-node
    environment:
      - NLSR_CONFIG=$TOPOLOGY_DIR/nodeD-nlsr.conf
      - GAME=$GAME_BASE nodeD
    volumes: 
      - $GAME_JAR_SRC:$GAME_JAR_DEST
      - $NLSR_CONFIG_SRC:$NLSR_CONFIG_DEST
    stdin_open: true
    tty: true
    networks:
      ndn:
        ipv4_address: 172.19.0.13

networks:
  ndn:
    external:
      name: ndn