version: '2'

services:
  ndn-game-l-A:
      image: ndn-node
      environment:
        - NLSR_CONFIG=/NLSR/topologies/linear/nodeA-nlsr.conf
      volumes: 
        - /home/stefano/projects/NdnGame:/NdnGameCode
        - /home/stefano/projects/ndn-script/nlsr:/NLSR
      stdin_open: true
      tty: true
      networks:
        ndn:
          ipv4_address: 172.19.0.10
  ndn-game-l-B:
      image: ndn-node
      environment:
        - NLSR_CONFIG=/NLSR/topologies/linear/nodeB-nlsr.conf
      volumes: 
        - /home/stefano/projects/NdnGame:/NdnGameCode
        - /home/stefano/projects/ndn-script/nlsr:/NLSR
      stdin_open: true
      tty: true
      networks:
        ndn:
          ipv4_address: 172.19.0.11

# networks:
#   ndn_game:
#     driver: bridge
#     driver_opts:
#       com.docker.network.enable_ipv6: "false"
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.30.18.0/24
#           gateway: 172.30.18.0
networks:
  ndn:
    external:
      name: ndn